const API_BASE_URL = import.meta.env.VITE_API_BASE_URL;

const API_AUTH_CONTROLLER = `${API_BASE_URL}/api/Auth`;
const API_USER_CONTROLLER = `${API_BASE_URL}/api/User`;
const API_PRODUCT_CONTROLLER = `${API_BASE_URL}/api/Product`;
const API_REVIEW_CONTROLLER = `${API_BASE_URL}/api/Review`;

export {API_AUTH_CONTROLLER, API_USER_CONTROLLER, API_PRODUCT_CONTROLLER, API_REVIEW_CONTROLLER};